# This class has methods for traversing the AST
class TreeTraverser :
    def __init__(self, node) :
        self.node = node

    # Chooses the appropriate method based on the type of node
    def traverseTree(self, node) :
        method = "visit" + node.node_type
        visitor = getattr(self, method, self.genericVisit) 
        return visitor(node)
    # If we dont specify the node type, then just visit its children
    def genericVisit(self, node) :
        for child in node.children :
            self.traverseTree(child)

# Generates asm based on the the type of node it encounters
# This prints the required asm instructions now
# Need to get it to hold all the asm
class CodeGenerator(TreeTraverser):
    def __init__(self):
        # Hold all of our assembly instructions generated by the traverser
        self.asm = []

    # Is this even necessary? Probably for later steps
    def visitConstant(self, node):
        return node.exp

    # The book is using different ASM syntax but I'm using NASM
    def visitReturn(self, node):
        retVal = node.children[0].exp
        self.asm.append(f"mov rax, 60")  
        self.asm.append(f"mov rdi, {retVal}")
        self.asm.append(f"syscall")

    # Get all the statements in our function call
    def visitFunction(self, node):
        self.asm.append(f"{node.functionName}:")
        for child in node.children:
            self.traverseTree(child)

    # Generate the required ASM to start and finish the program
    def visitProgram(self, node):
        self.asm.append("; Generated program by compilerDriver")
        self.asm.append("section .text")
        self.asm.append("global main")   

        for child in node.children:
            self.traverseTree(child)

        self.asm.append("section .note.GNU-Stack")
        self.asm.append("; End prog")







    




